import { Project } from '@shared/schema';

export const customProjects: Project[] = [
  {
    id: 1001,
    title: "Dubai Marina Tower",
    description: "Luxury residential tower in the heart of Dubai Marina with premium amenities and stunning views.",
    shortDescription: "Premium residential tower in Dubai Marina",
    location: "Dubai Marina, UAE",
    category: "RESIDENTIAL",
    propertyType: "APARTMENT",
    roi: "12.50",
    minInvestment: 50000,
    targetAmount: 5000000,
    currentAmount: 3000000,
    status: "FUNDING",
    featured: false,
    priority: 0,
    propertySize: 1200,
    bedrooms: 2,
    bathrooms: 2,
    floors: 25,
    parkingSpaces: 1,
    expectedCompletionDate: "2024-12-31",
    monthlyRent: 8000,
    annualAppreciation: "5.20",
    imageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    gallery: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400"],
    videoUrl: null,
    latitude: "25.0920",
    longitude: "55.1381",
    address: "Dubai Marina, Dubai, UAE",
    city: "Dubai",
    state: "Dubai",
    country: "UAE",
    postalCode: "00000",
    constructionStartDate: "2023-01-01",
    constructionEndDate: "2024-12-31",
    tags: ["luxury", "residential", "marina"],
    amenities: ["gym", "pool", "parking", "security"],
    documents: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1002,
    title: "Singapore Business Hub",
    description: "Modern office complex in Singapore's premier business district with high rental yields.",
    shortDescription: "Modern office complex in Singapore CBD",
    location: "Singapore CBD, Singapore",
    category: "COMMERCIAL",
    propertyType: "OFFICE",
    roi: "15.20",
    minInvestment: 100000,
    targetAmount: 8000000,
    currentAmount: 8000000,
    status: "COMPLETE",
    featured: true,
    priority: 1,
    propertySize: 5000,
    bedrooms: null,
    bathrooms: 8,
    floors: 15,
    parkingSpaces: 20,
    expectedCompletionDate: "2023-06-30",
    monthlyRent: 50000,
    annualAppreciation: "7.50",
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    gallery: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400"],
    videoUrl: null,
    latitude: "1.3521",
    longitude: "103.8198",
    address: "Singapore CBD, Singapore",
    city: "Singapore",
    state: null,
    country: "Singapore",
    postalCode: "00000",
    constructionStartDate: "2022-01-01",
    constructionEndDate: "2023-06-30",
    tags: ["commercial", "office", "cbd"],
    amenities: ["parking", "security", "conference rooms"],
    documents: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1003,
    title: "London Tech District",
    description: "Industrial warehouse facility with long-term lease agreements and stable returns.",
    shortDescription: "Industrial warehouse in London",
    location: "London, UK",
    category: "INDUSTRIAL",
    propertyType: "WAREHOUSE",
    roi: "8.75",
    minInvestment: 25000,
    targetAmount: 3000000,
    currentAmount: 1500000,
    status: "FUNDING",
    featured: false,
    priority: 0,
    propertySize: 10000,
    bedrooms: null,
    bathrooms: 2,
    floors: 1,
    parkingSpaces: 10,
    expectedCompletionDate: "2024-03-31",
    monthlyRent: 15000,
    annualAppreciation: "3.20",
    imageUrl: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    gallery: ["https://images.unsplash.com/photo-1465101046530-73398c7f28ca?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400"],
    videoUrl: null,
    latitude: "51.5074",
    longitude: "-0.1278",
    address: "London, UK",
    city: "London",
    state: null,
    country: "UK",
    postalCode: "00000",
    constructionStartDate: "2023-03-01",
    constructionEndDate: "2024-03-31",
    tags: ["industrial", "warehouse", "logistics"],
    amenities: ["loading dock", "security", "parking"],
    documents: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
